Name: Build HEZWIN (Final Version)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
<<<<<<< HEAD
        submodules: recursive
        fetch-depth: 0
=======
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Go (HEZWIN İçin Gerekli)
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '12266719'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973"
        echo "NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973" >> $GITHUB_ENV
>>>>>>> 41396f4d (ui tunnel gradle guncellendi)

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
<<<<<<< HEAD
        distribution: temurin
        java-version: 17

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        yes | sdkmanager "ndk;27.0.12077973"
        echo "NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973" >> $GITHUB_ENV

    - name: Build Debug APK
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        chmod +x gradlew
        ./gradlew assembleDebug
=======
        distribution: 'temurin'
        java-version: '17'

    - name: Build Debug APK
      run: |
        # Eğer dosyalar bir alt klasördeyse oraya gir, değilse hata verme
        [ -d "hezwin-android-master" ] && cd hezwin-android-master || echo "Ana dizindeyiz"
        
        # Gradle dosyalarını kontrol et ve çalıştır
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        
        # Gradle Wrapper'ın varlığını zorla doğrula
        if [ ! -f "gradlew" ]; then
          echo "HATA: gradlew dosyası bulunamadı! Lütfen dosya konumunu kontrol et."
          exit 1
        fi
        
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
>>>>>>> 41396f4d (ui tunnel gradle guncellendi)

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: HEZWIN-Debug-APK
<<<<<<< HEAD
        path: ui/build/outputs/apk/debug/*.apk
=======
        # Alt klasör ihtimaline karşı yıldız kullanımı
        path: "**/ui/build/outputs/apk/debug/*.apk"

>>>>>>> 9a6b38aa (Update build.yml)
